version: '3.8'
services:
  db:
    image: postgres:15
    container_name: catbox-db
    environment:
      POSTGRES_USER: catbox_user
      POSTGRES_PASSWORD: catbox_password
      POSTGRES_DB: catbox_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: